Add a missing header file
Fixes:

.../app/apptest_cmp.cc(52): error: namespace "std" has no member "runtime_error"
      throw std::runtime_error("The field sizes do not match.");