Added missing cassert include
Fixes the following error:
    portage/portage/state/state_manager.h:435:5: error: there are no arguments to 'assert' that depend on a template parameter, so a declaration of 'assert'
must be available [-fpermissive]
      assert(this->material_cells_.find(m)!=this->material_cells_.end());